# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CLoss <- function(Y, X, Dstar, beta) {
    .Call('KoulMde_CLoss', PACKAGE = 'KoulMde', Y, X, Dstar, beta)
}

DY <- function(Y, D) {
    .Call('KoulMde_DY', PACKAGE = 'KoulMde', Y, D)
}

GVec <- function(PMat) {
    .Call('KoulMde_GVec', PACKAGE = 'KoulMde', PMat)
}

HVec <- function(PMat) {
    .Call('KoulMde_HVec', PACKAGE = 'KoulMde', PMat)
}

GLI <- function(E, n, SN, EN) {
    .Call('KoulMde_GLI', PACKAGE = 'KoulMde', E, n, SN, EN)
}

PV <- function(SE, nlen) {
    .Call('KoulMde_PV', PACKAGE = 'KoulMde', SE, nlen)
}

GUI <- function(E, n, SN, EN) {
    .Call('KoulMde_GUI', PACKAGE = 'KoulMde', E, n, SN, EN)
}

Xpm <- function(X) {
    .Call('KoulMde_Xpm', PACKAGE = 'KoulMde', X)
}

PMM <- function(n, DYM, XpmM, l, p, bVec) {
    .Call('KoulMde_PMM', PACKAGE = 'KoulMde', n, DYM, XpmM, l, p, bVec)
}

